# Generated by Django 4.2.4 on 2023-09-11 19:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreetNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('n_street_edges', models.IntegerField()),
            ],
            options={
                'db_table': 'street_node',
            },
        ),
        migrations.CreateModel(
            name='StreetEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField()),
                ('from_street_node_id', models.IntegerField()),
                ('to_street_node_id', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'db_table': 'street_edge',
            },
        ),
    ]
