# Generated by Django 4.2.4 on 2023-08-23 23:16

from django.db import migrations
from django.contrib.gis.geos import GEOSGeometry
import json

def upload_intersection_features(apps, schema_editor):
    Intersection = apps.get_model('here_i_am', 'Intersection')

    with open('here_i_am/data/toronto-intersections.geojson') as data_file:
        intersections_json = json.load(data_file)
        features = intersections_json['features']
        for feature in features:
            properties = feature['properties']
            properties['geom'] = GEOSGeometry(json.dumps(feature['geometry']))
            Intersection(**properties).save()

def delete_all_intersections(apps, schema_editor):
    Intersection = apps.get_model('here_i_am', 'Intersection')
    Intersection.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('here_i_am', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(upload_intersection_features, delete_all_intersections),
    ]

