# Generated by Django 4.2.4 on 2023-08-24 00:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('here_i_am', '0002_auto_20230823_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreetSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField()),
                ('from_intersection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='street_segments_from', to='intersection')),
                ('to_intersection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='street_segments_to', to='intersection')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'db_table': 'street_segment',
            },
        ),
    ]
